In [ ]:
# from frenztoolkit.reader import load_experiment
import matplotlib.pyplot as plt
import numpy as np
num_columns = 6  # This must match how it was saved
eeg_data_type = np.float32  # Must match EEG_DATA_TYPE used for saving

loaded_eeg_flat = np.fromfile(
    "recorded_data/20250506_233230_327488/custom_eeg.dat", dtype=eeg_data_type)
# Reshape back into (num_samples, num_columns)
# You'll need to know the total number of samples, or calculate it
if loaded_eeg_flat.size % num_columns == 0:
    num_samples_loaded = loaded_eeg_flat.size // num_columns
    loaded_eeg_reshaped = loaded_eeg_flat.reshape(
        num_samples_loaded, num_columns)
    print(loaded_eeg_reshaped.shape)
else:
    print("Error: Cannot reshape, total elements not divisible by num_columns.")

print(loaded_eeg_reshaped[:5])


(69606, 6)
[[ 32331. 134232.      0.   3167.  97644.      0.]
 [ 32334. 133399.      0.   3169.  94064.      0.]
 [ 32345. 134091.      0.   3189.  96986.      0.]
 [ 32347. 133449.      0.   3163.  94321.      0.]
 [ 32329. 133447.      0.   3131.  94182.      0.]]


In [ ]:
# # Load the recorded session from your experiment folder
# # find the folder contains your recorded data by timestamp
# session_data = load_experiment("recorded_data/1746664210.2801862")

# # Access EEG and POAS score history
# eeg = session_data["DATA"]["RAW"]["EEG"]
# poas_list = session_data["SCORE"]["array__posture"]
# print(eeg.shape)
# print(eeg[:])

(5688, 6)
[[0.        6.6229553 0.        7.6384277 0.        0.       ]
 [0.        6.4087524 0.        7.4002686 0.        0.       ]
 [0.        6.6210938 0.        7.627571  0.        0.       ]
 ...
 [0.        6.430908  0.        7.4586334 0.        0.       ]
 [0.        6.6084595 0.        7.6183014 0.        0.       ]
 [0.        6.435425  0.        7.191086  0.        0.       ]]
