In [1]:
from frenztoolkit.reader import load_experiment
import matplotlib.pyplot as plt
import numpy as np

file_path = 'recorded_data/E244GH55FX1U_1737363746000/E244GH55FX1U_1737363746000.dat'


data = np.fromfile(file_path, dtype=np.float32)

# 重塑数据为 (samples, channels)
eeg = data.reshape(-1, 6)

print("Data shape:", eeg.shape)
print("Data Preview:")
print(eeg[10:15])

/Users/suryaven/Documents/code/uni/neurotech/frenztoolkit/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(


Data shape: (4475652, 6)
Data Preview:
[[1.1004e-41 0.0000e+00 1.1014e-41 0.0000e+00 1.1021e-41 0.0000e+00]
 [1.1011e-41 0.0000e+00 1.1035e-41 0.0000e+00 1.1024e-41 0.0000e+00]
 [1.1034e-41 0.0000e+00 1.1038e-41 0.0000e+00 1.1060e-41 0.0000e+00]
 [1.1013e-41 0.0000e+00 1.1067e-41 0.0000e+00 1.1049e-41 0.0000e+00]
 [1.1059e-41 0.0000e+00 1.1056e-41 0.0000e+00 1.1080e-41 0.0000e+00]]
